cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/',views.cart_add, name = 'cart_add'),
    path('remove/<product_id>/',views.cart_remove, name = 'cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls', namespace = 'cart')),
    path('order/',include('orders.urls',namespace = 'orders')),   
    path('payment/',include('payment.urls', namespace = 'payment')),
    path('',include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/',views.payment_process, name = 'process'),
    path('completed/',views.payment_completed, name = 'completed'),
    path('canceled/',views.payment_canceled, name = 'canceled'),    
    path('stripe_webhook/', views.stripe_webhook, name = 'stripe-webhook')
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from decimal import Decimal
from math import e
from django.http import HttpResponse
import stripe
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from orders.models import Order
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from payment.tasks import task_paid_canceled, task_paid_success

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id = order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode':'payment',
            'client_reference_id':order.id,
            'success_url':success_url,
            'cancel_url':cancel_url,
            'line_items':[]
        }
        for item in order.products.all():
            session_data['line_items'].append({
                'price_data':{
                    'unit_amount':int(item.price * Decimal('100')),
                    'currency':'usd',
                    'product_data':{
                        'name':item.product.name,
                    },
                },
                'quantity':item.quantity,
            })
        if order.coupons:
            stripe_coupon = stripe.Coupon.create(name = order.coupons.code, percent_off = order.discount, duration='once')
            session_data['discounts'] = [{
                'coupon':stripe_coupon.id
            }]
        session = stripe.checkout.Session.create(**session_data)
        
        return redirect(session.url, code = 303)
    else:
        return render(request, 'components/payment/process.html',locals())
    
def payment_completed(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id = order_id)
    task_paid_success.delay(order.id)
    return render(request, 'components/payment/completed.html')

def payment_canceled(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id = order_id)
    task_paid_canceled.delay(order.id)
    return render(request, 'components/payment/canceled.html')

@require_POST
@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    signature_header = request.META("HTTP_STRIPE_SIGNATURE")
    endpoint_secret = settings.STRIPE_WEBHOOK_SECRET
    event = None
    try:
        event = stripe.Webhook.construct_event(payload, signature_header, endpoint_secret) 
    except:
        return HttpResponse(status = 400)
    
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        print(f"{session.mode} {session.payment_status}")
        if session.mode == 'payment' and session.payment_status == 'paid':
            try:
                order = Order.objects.get(id = session.client_reference_id)
            except Order.DoesNotExist:
                return HttpResponse(status = 400)
            order.payable = True
            order.save()
    return HttpResponse(status = 200)
        

templates/components/payment/canceled.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid product-page">
        <div class="div-product d-flex justify-content-center align-items-center h-100 flex-column ">
            <div class="product-blur h-50 w-25"></div>
            <div class="d-flex justify-content-center align-items-center h-50 flex-column inner-product">
                <h1 class="fw-5 text-white text-center h-product">Canceled Paid</h1>
                <h6 class="fw-5 text-white text-center h-nav-product">
                    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'categories_url' %}" class="breadcrumb-nav-page"><i class="bi bi-house-fill"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-nav-page fs-6">Canceled Paid</a></li>
                        </ol>
                    </nav>
                </h6>
            </div>
        </div>
    </div>
    <div class="container-lg text-start p-5">
        <div class='complete-card'>
            <h4 class="text-center pb-2 text-danger description-text">Payment Failed</h4>
            <p class='text-center text-secondary'>An error occurred during payment, please try again</p>
            <p class='text-center'>
                <a class='btn btn-sm btn-outline-secondary rounded-0 w-25' href="{% url 'categories_url'%}">Continue</a>
            </p>
        </div>
    </div>
{% endblock content %}

templates/components/payment/completed.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid product-page">
        <div class="div-product d-flex justify-content-center align-items-center h-100 flex-column ">
            <div class="product-blur h-50 w-25"></div>
            <div class="d-flex justify-content-center align-items-center h-50 flex-column inner-product">
                <h1 class="fw-5 text-white text-center h-product">Complete Paid</h1>
                <h6 class="fw-5 text-white text-center h-nav-product">
                    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'categories_url' %}" class="breadcrumb-nav-page"><i class="bi bi-house-fill"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-nav-page fs-6">Complete Paid</a></li>
                        </ol>
                    </nav>
                </h6>
            </div>
        </div>
    </div>
    <div class="container-lg text-start p-5">
        <div class='complete-card'>
            <h4 class="text-center pb-2 text-success description-text">Successful Paid</h4>
            <p class='text-center text-secondary'>Payment was successful,the manager will contact you regarding the order.</p>
            <p class='text-center'>
                <a class='btn btn-sm btn-outline-secondary rounded-0 w-25' href="{% url 'categories_url'%}">Continue</a>
            </p>
        </div>
    </div>
{% endblock content %}

templates/components/payment/process.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid product-page">
        <div class="div-product d-flex justify-content-center align-items-center h-100 flex-column ">
            <div class="product-blur h-50 w-25"></div>
            <div class="d-flex justify-content-center align-items-center h-50 flex-column inner-product">
                <h1 class="fw-5 text-white text-center h-product">Order summary</h1>
                <h6 class="fw-5 text-white text-center h-nav-product">
                    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'categories_url' %}" class="breadcrumb-nav-page"><i class="bi bi-house-fill"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-nav-page fs-6">Order summary</a></li>
                        </ol>
                    </nav>
                </h6>
            </div>
        </div>
    </div>
    <div class="container-lg text-start p-5">
        <div class='row'>
            <div class='col-12'>
                <h4 class="text-start pb-2 description-text">Order summary</h4>
                <table class="table table-secondary table-hover">
                    <thead> 
                        <tr class="table-secondary text-center">
                            <th scope="col" class="image-th">Image</th>
                            <th scope="col" style='width:24rem'>Name</th>
                            <th scope="col" style='width:18rem'>Quantity</th>
                            <th scope="col">Unit Price</th>
                            <th scope="col">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order.products.all %}
                            <tr class='table-light text-center align-content-center'>
                                <th scope="row"><img src="{{ item.product.image.url }}" class="img-thumbnail img-cart"/></th>
                                <td class='text-start'>
                                    <h6>{{ item.product.name}}</h6>
                                    <p class='text-secondary' style='font-size:12px;'>{{item.product.description|truncatewords:50}}</p>
                                </td>
                                <td>
                                    {{ item.quantity}}
                                </td>
                                <td>{{ item.price }}$</td>
                                {% if cart.coupon %}
                                <td>
                                    <p><span class='text-decoration-line-through'>{{ item.get_cost }}$</span> - {{cart.coupon.discount}}%</p> 
                                    <p>{{order.get_total_cost|floatformat:2}}$</p>
                                </td>
                                {% else %}
                                <td>{{ item.get_cost }}$</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        <tr class='table-secondary text-end'>
                            <th scope="row" colspan='4'>Total Price</th>
                            <td scope="row">{{ order.get_total_cost|floatformat:2}}$</td>
                        </tr>
                    </tbody>
                </table>
                <form active="{% url 'payment:process'%}" method="POST" class='text-end'>
                    {% csrf_token %}
                    <input type='submit' class='btn btn-success rounded-0 ' value='Pay'/>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}