cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/',views.cart_add, name = 'cart_add'),
    path('remove/<product_id>/',views.cart_remove, name = 'cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls', namespace = 'cart')),
    path('order/',include('orders.urls',namespace = 'orders')),   
    path('payment/',include('payment.urls', namespace = 'payment')),
    path('',include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.order_create, name = 'order_create'),
    path('done/', views.order_done, name = 'order_done'),
    path('order/<order_id>/', views.admin_order_detail, name='order_detail')
]

orders/models.py
from decimal import Decimal
import uuid
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from shop.models import Coupon, Product

# Create your models here.
class Order(models.Model):
    POST_USE = [
        ('UK','UrkPost'),
        ('NW','NewPost'),
    ]
    PAID_USE = [
        ('card','Card'),
        ('delivery','Delivery'),
    ]
    coupons = models.ForeignKey(Coupon, on_delete = models.SET_NULL, blank = True, null = True, related_name = 'orders_coupons')
    discount = models.IntegerField(default = 0, blank = True, null = True, validators = [MinValueValidator(0),MaxValueValidator(100)])
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    email = models.EmailField()
    number = models.CharField(max_length = 20)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length = 100)
    post = models.CharField(choices = POST_USE,blank = False, default = 'NW')
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    paid = models.CharField(choices = PAID_USE, blank = False, default = 'card') 
    
    payable = models.BooleanField(default = False)
    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields = ['-created'])]
        
    def __str__(self):
        return f"Order №{str(self.id)}"
    
    def get_total_cost(self):
        return self.get_total_cost_discount() - self.get_discount()
    
    def get_total_cost_discount(self):
        return sum(item.get_cost() for item in self.products.all())
    
    def get_discount(self):
        total_cost = self.get_total_cost_discount()
        if self.discount:
            return total_cost * (self.discount / Decimal(100))
        return Decimal(0)
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE, related_name = 'products')
    
    product = models.ForeignKey(Product, on_delete = models.CASCADE, related_name = 'order_products')
    quantity = models.PositiveIntegerField(default = 1)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    
    
    def __str__(self):
        return f"{self.pk}"
    
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from django.forms import modelform_factory
from .models import Order, OrderProduct


class OrderAdd(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['created','updated']
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control bg-body-secondary',"id":"id_first_name","placeholder":"First Name"}),
            'last_name':forms.TextInput(attrs={'class':'form-control bg-body-secondary',"id":"id_last_name","placeholder":"Last Name"}),
            'email':forms.EmailInput(attrs={'class':'form-control bg-body-secondary',"id":"id_email","placeholder":"Email"}),
            'number':forms.TextInput(attrs={'class':'form-control bg-body-secondary',"id":"id_number","placeholder":"Number"}),
            'postal_code':forms.TextInput(attrs={'class':'form-control bg-body-secondary','id':'floatingInputValue1'}),
            'city':forms.TextInput(attrs={'class':'form-control bg-body-secondary','id':'floatingInputValue2'}),
            'post':forms.RadioSelect(attrs={'class':'form-check-input','id':'gridRadios1'}),
            'paid':forms.RadioSelect(attrs={'class':'form-check-input','id':'gridRadios2'},)
        }

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http.response import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from shop.forms import CouponField
from shop.models import Product
from .cart import Cart
from .form import CartField

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CartField(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity = int(cd['quantity']), override=cd['override'])
    return redirect('cart:cart_detail')
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['item_override'] = CartField(initial={'quantity':item['quantity'], 'override':True})
    coupon_form = CouponField()
    context = {"cart":cart,
               'coupon_form':coupon_form}
    return render(request, 'components/cart.html',context)
# Create your views here.

orders/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse

from orders.tasks import task_order_create
from .models import Order, OrderProduct 
from cart.cart import Cart
from .forms import OrderAdd
# Create your views here.

def order_done(request):
    return render(request, 'components/include/order_done.html')

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderAdd(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupons = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderProduct.objects.create(
                    order=order,
                    product=item['product'],
                    quantity=item['quantity'],
                    price=item['price']
                )
            cart.clear()
            task_order_create.delay(order.id)
            if order.paid == "delivery":
                return redirect('orders:order_done')
            else:
                request.session['order_id'] = order.id
                return redirect(reverse('payment:process'))
    else:
        form = OrderAdd()

    context = {
        'cart': cart,
        'form': form,
    }
    return render(request, 'components/orders.html', context)


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    return render(request, 'components/include/orders_detail.html',{'order':order})
    

templates/components/cart.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid product-page">
        <div class="div-product d-flex justify-content-center align-items-center h-100 flex-column ">
            <div class="product-blur h-50 w-25"></div>
            <div class="d-flex justify-content-center align-items-center h-50 flex-column inner-product">
                <h1 class="fw-5 text-white text-center h-product">Cart</h1>
                <h6 class="fw-5 text-white text-center h-nav-product">
                    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'categories_url' %}" class="breadcrumb-nav-page"><i class="bi bi-house-fill"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-nav-page fs-6">Cart</a></li>
                        </ol>
                    </nav>
                </h6>
            </div>
        </div>
    </div>
    <div class="container-lg text-start p-5">
        <div class='row'>
            <div class='col-12'>
                <div class='row'>
                    <div class='col-12'>                        
                        {% if cart %}
                        <h4 class="text-start pb-2 description-text">Products Cart</h4>
                        {% if cart.get_total_price < 2%}
                            <div class="alert alert-danger alert-dismissible fade show position-relative" role="alert">
                                <div class='position-absolute top-25'>
                                    <i class="bi bi-exclamation-triangle fs-5"></i>
                                </div>
                                <span class='ps-4'>To place an order, you must collect at least <strong>2$</strong>! </span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <table class="table table-secondary table-hover">
                            <thead> 
                                <tr class="table-secondary text-center">
                                    <th scope="col" class="image-th">Image</th>
                                    <th scope="col" style='width:24rem'>Name</th>
                                    <th scope="col" style='width:18rem'>Quantity</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr class='table-light text-center align-content-center'>
                                            <th scope="row"><img src="{{ product.image.url }}" class="img-thumbnail img-cart"/></th>
                                            <td class='text-start'>
                                                <h6>{{ product.name}}</h6>
                                                <p class='text-secondary' style='font-size:12px;'>{{product.description|truncatewords:50}}</p>
                                            </td>
                                            <td>
                                                <div class="d-flex justify-content-start w-75">
                                                    <form action="{% url 'cart:cart_add' product.id%}" method="POST">
                                                        <div class="input-group mb-3">
                                                            {% csrf_token %}
                                                                {% for field in item.item_override %}
                                                                    {{ field}}
                                                                {% endfor %}
                                                            <button type="submit" class="btn text-dark rounded-0 "><i class="bi bi-arrow-clockwise"></i></button>                                                    
                                                        </div>  
                                                    </form> 
                                                    <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                                                        <div class="input-group mb-3">
                                                            {% csrf_token %}
                                                            <button type="submit" class="btn text-danger rounded-0 "><i class="bi bi-trash3"></i></button>
                                                        </div>  
                                                    </form> 
                                                </div>
                                            </td>
                                            <td>{{ item.price }}$</td>
                                            <td>{{ item.total_price }}$</td>
                                        </tr>
                                    {% endwith %}
                                {% endfor %}
                                <tr class='table-secondary text-end'>
                                    <th scope="row" colspan='4'>Total Price</th>
                                    <td scope="row">{{ cart.get_total_price}}$</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class='col-4'>
                        <div class="accordion accordion-flush" id="accordionFlushExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                <button class="accordion-button collapsed text-uppercase fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                                    Use coupon for purchase
                                </button>
                                </h2>
                                <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                                    <div class="accordion-body">
                                        <p>Enter the coupon name to get a discount on the product</p>
                                        <form method="POST" action="{% url 'coupon_apply'%}">
                                            <div class="input-group mb-3">
                                                <button class="btn btn-outline-secondary" type="submit" id="button-addon1">Used</button>
                                                {{ coupon_form.code }}
                                            </div>
                                            {% csrf_token %}
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='col-3 ms-auto'>
                        <table class="table">
                            <tbody>
                                {% if cart.coupon %}
                                    <tr>
                                        <th scope="row">Discount</th>
                                        <td>-{{cart.coupon.discount}}%</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">{{cart.coupon.code }}*</th>
                                        <td>-{{cart.get_discount|floatformat:2}}$</td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <th scope="row">Total Price</th>
                                    <td>{{cart.get_total_discount_price|floatformat:2}}$</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class='col-12'>
                        <div class='row'>
                            <div class='col-6'>
                                <p class='text-start'>
                                    <a class='btn btn-sm btn-secondary rounded-0 w-25' href="{% url 'categories_url'%}">Continue</a>
                                </p>
                            </div>
                            <div class='col-6'>
                                <p class='text-end'>
                                    <a class='btn btn-sm btn-secondary rounded-0 w-25' 
                                    href="{% if cart.get_total_price < 2%}
                                            {% url 'cart:cart_detail'%}
                                        {% else %}
                                            {% url 'orders:order_create'%}
                                        {% endif %}">Checkout</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
                <div class='col-12'>
                    <h4 class="text-center pb-2 description-text">Products Cart</h4>
                    <p class='text-center text-secondary'>Cart is Empty</p>
                    <p class='text-center'>
                        <a class='btn btn-sm btn-secondary rounded-0 w-25' href="{% url 'categories_url'%}">Continue</a>
                    </p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/components/main-page-search.html
{% extends "base.html" %}

{% block content %}
    {% include "components/include/heading-page-tea.html" %}

    <div class="container-fluid text-center p-5">
        <div class="row">
            {% include "components/include/aside.html" with category=category categories=categories form_search=form query=query %}
            <div class="col-md-9 my-4">
                <div class="row row-cols-2 row-cols-lg-5 row-cols-md-4 row-cols-sm-3 gap-2 gap-lg-5">
                    {% for product in results %}
                    <div class="col-3">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <img src="{{ product.image.url}}" />
                                    <h6>{{ product.name }}</h6>
                                    <p class="fs-4">{{product.price}}$</p>
                                </div>
                                <div class="flip-card-back">
                                    <h3>{{ product.name }}</h3>
                                    <p class='flip-text'>{{ product.description|truncatewords:20}}</p>
                                    <a href="{% url 'product_url' product.slug product.pk%}" class="btn btn-secondary">View</a>
                                    <a href="" class="btn"><i class="bi bi-bag-fill"></i></a>
                                    <a href="" class="btn"><i class="bi bi-suit-heart"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
{% endblock content %}

templates/components/main-page.html
{% extends "base.html" %}

{% block content %}
    {% include "components/include/heading-page-tea.html" %}

    <div class="container-fluid text-center p-5">
        <div class="row">
            {% include "components/include/aside.html" with category=category categories=categories form_search=form_search%}
            <div class="col-md-9 my-4">
                <div class="row row-cols-2 row-cols-lg-5 row-cols-md-4 row-cols-sm-3 gap-2 gap-lg-5">
                    {% for product in products %}
                    <div class="col-3">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <img src="{{ product.image.url}}" />
                                    <h6>{{ product.name }}</h6>
                                    <p class="fs-4">{{product.price}}$</p>
                                </div>
                                <div class="flip-card-back">
                                    <h3>{{ product.name }}</h3>
                                    <p class='flip-text'>{{ product.description|truncatewords:20}}</p>
                                    <a href="{% url 'product_url' product.slug product.pk%}" class="btn btn-secondary">View</a>
                                    <a href="" class="btn"><i class="bi bi-suit-heart"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <nav aria-label="Page navigation example" class="my-3">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock content %}

templates/components/orders.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid product-page">
        <div class="div-product d-flex justify-content-center align-items-center h-100 flex-column ">
            <div class="product-blur h-50 w-25"></div>
            <div class="d-flex justify-content-center align-items-center h-50 flex-column inner-product">
                <h1 class="fw-5 text-white text-center h-product">Order goods</h1>
                <h6 class="fw-5 text-white text-center h-nav-product">
                    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'categories_url' %}" class="breadcrumb-nav-page"><i class="bi bi-house-fill"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'cart:cart_detail' %}" class="breadcrumb-nav-page fs-6">Cart</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-nav-page fs-6">Orders</a></li>
                        </ol>
                    </nav>
                </h6>
            </div>
        </div>
    </div>
    <div class="container-lg text-start p-5">
        <form class="{% url 'orders:order_create'%}" method="POST">
            <div class="row">
                <h4 class="text-start pb-2 description-text">Orders Goods</h4>
                <div class='col-6'>
                    <div class="card border-0">
                        <div class="card-header bg-body-secondary rounded-0 header-card">
                            <div class='rect-icon'>
                                <i class="bi bi-person-fill-add"></i>
                            </div>
                            <p class='order-personal-data ps-5 text-uppercase'>Personal data</p>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="row gap-3">
                                <div class="col">
                                    {{ form.first_name }}
                                </div>
                                <div class="col">
                                    {{ form.last_name }}
                                </div>
                                <div class="col-12">
                                    {{ form.email }}
                                </div>
                                <div class="col-12">
                                    {{ form.number }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card border-0">
                        <div class="card-header bg-body-secondary rounded-0 header-card">
                            <div class='rect-icon'>
                                <i class="bi bi-send-fill"></i>
                            </div>
                            <p class='order-personal-data ps-5 text-uppercase'>Delivery method</p>
                        </div>
                        <div class="card-body">
                            <div class="row gap-3">
                                <div class="col-12">
                                    {% for radio in form.post %}
                                        <div class="form-check">
                                            {{ radio.tag }}
                                            <label class="form-check-label" for="{{ radio.id_for_label }}">
                                                {% if radio.choice_label == 'UrkPost'%}
                                                    <strong>Ukr Poshta</strong>. Goods are delivered within 3-6 days throughout Ukraine. Shipping only upon prepayment.
                                                {% else %}
                                                    <strong>Nova Poshta</strong>. Goods are delivered within 1-2 days throughout Ukraine.
                                                {% endif %}
                                            </label>
                                        </div>                                        
                                    {% endfor %}
                                </div>
                                <div class="col-12">
                                    <div class="form-floating">
                                        {{ form.city }}
                                        <label for="floatingInputValue2">City</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating">
                                        {{ form.postal_code }}
                                        <label for="floatingInputValue1">Postal Code</label>
                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class='col-6'>
                    <div class="card border-0">
                        <div class="card-header bg-body-secondary rounded-0 header-card">
                            <div class='rect-icon'>
                                <i class="bi bi-cart-dash"></i>
                            </div>
                            <p class='order-personal-data ps-5 text-uppercase'>Payment card</p>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Name</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Unite Price</th>
                                        <th scope="col">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                    <tr>
                                        <td>{{ item.product.name}}</td>
                                        <td>{{ item.quantity}}</td>
                                        <td>{{ item.price }}$</td>
                                        <td>{{ item.total_price|floatformat:2 }}$</td>
                                    </tr>
                                    {% endfor %}
                                    {% if cart.coupon %}
                                        <tr>
                                            <td colspan="3">Discount <strong>-{{cart.coupon.discount}}%</strong></td>
                                            <td>-{{ cart.get_discount|floatformat:2}}$</td>
                                        </tr>
                                    {% endif %}
                                    <tr>
                                        <td colspan="3"><strong>Total Price</strong></td>
                                        <td>{{ cart.get_total_discount_price|floatformat:2}}$</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card border-0">
                        <div class="card-header bg-body-secondary rounded-0 header-card">
                            <div class='rect-icon'>
                                <i class="bi bi-credit-card-2-back-fill"></i>
                            </div>
                            <p class='order-personal-data ps-5 text-uppercase'>Payment method</p>
                        </div>
                        <div class="card-body">
                            <div class="row gap-3">
                                <div class="col-12">
                                    {% for radio in form.paid %}
                                        <div class="form-check">
                                            {{ radio.tag }}
                                            <label class="form-check-label" for="{{ radio.id_for_label }}">
                                                {% if radio.choice_label == 'Card'%}
                                                    Payment Visa, MasterCard
                                                {% else %}
                                                    Cash on delivery
                                                {% endif %}
                                            </label>
                                        </div>                                        
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <input type='submit' class='btn btn-secondary w-25 ms-auto rounded-0 text-uppercase' value='Confirm order'/>
            </div>
        </form>
    </div>
{% endblock content %}